CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stats (
    user_id TEXT PRIMARY KEY,
    attack INTEGER DEFAULT TBD,
    hp INTEGER DEFAULT TBD,
    defense INTEGER DEFAULT TBD,
    clears INTEGER DEFAULT 0,
    score INTEGER DEFAULT 0,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stats_score ON stats(score);

CREATE INDEX IF NOT EXISTS idx_stats_clears ON stats(clears);